### ISSUE TITLE
auto_bone_controller blender 2.78 random errors...

### ISSUE THREAD

**Issue by razvanc-r** [Antonioya/blender#52]
Some times I'm getting this error

```py
Traceback (most recent call last):
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 302, in execute
    self.set_bone(context, ob, amt, main_bone, size_a, txt_a, size_b, txt_b)
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 240, in set_bone
    self.create_controllers(amt, main_bone, txt_a, txt_b, size_a, size_b, bx, bz, roll)
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 118, in create_controllers
    self.report({'INFO'}, 'create_controllers, {}'.format(type(main_bone.name)))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

location: <unknown location>:-1
```

and sometimes I'm getting this error:

```py
Traceback (most recent call last):
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 297, in execute
    self.set_bone(context, ob, amt, main_bone, size_a, txt_a, size_b, txt_b)
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 239, in set_bone
    self.set_custom_shapes(context, ob, main_bone, main_name, txt_a, txt_b)
  File "/home/razvan/.config/blender/2.78/scripts/addons/auto_bone_controller.py", line 150, in set_custom_shapes
    bpy.data.objects[ob.name].data.edit_bones[main_bone.name].bbone_segments = scene.auto_bone_subdivisions
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1
```

I'm not sure if they're blender related or your script, I think it's blender but I have no idea how I should report this issue upstream... if you have any ideas please let me know :)

**Comment by Antonioya** [comment]
I had these type of errors sometimes, but I was unable to find the reason.

What I noticed is: If you "reselect" the bone before press the button, usually it works fine.

Thanks for the report, I will investigate if I can find the reason and fix it.

**Comment by razvanc-r** [comment]
This looks to me more like an upstream problem in blender than something wrong with your script. Also the 'reselect' trick doesn't work for me, just tried it...
