### ISSUE TITLE
Auto Bone Controller - Can't Enable the Addon

### ISSUE THREAD

**Issue by ruivo** [Antonioya/blender#61]
Hi Antonioya, I highly aprecciate your work,
This is the error I get when trying to enable the addon on MacOS 10.11.6 - Blender 2.78c:

---------------------------------------

bpy.data.window_managers["WinMan"].addon_search = "auto"
Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/Users/cg/Library/Application Support/Blender/2.78/scripts/addons/addon_auto_bone_controller.py", line 429
    register();
           ^
IndentationError: expected an indented block

**Comment by BugBilly** [comment]
when I install the addon it doesnt appear in my list to enable it
